## Aljabar Matrix

#### Pengertian Matriks

- Matrix adalah kumpulan bilangan maupun bilangan kompleks yang tersusun dalam bentuk beberapa baris dan beberapa kolom yang dibungkus dengan kurung () atau kurung [].

Contoh bentuk matriks : 

$
A =\begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}
$

Matriks mempunyai ukuran yang ditentukan oleh jumlah baris dan jumlah kolom. Dalam notasi umum matriks, nama dari sebuah matriks biasanya berupa sebuah huruf kapital, jumlah baris biasanya dicantumkan terlebih dahulu.

Maksudnya :

$A_{ij}$

Matrik diatas mempunyai sebanyak i baris dan sebanyak j kolom.

Elemen matriks dinyatakan dengan huruf kecil dengan subskrip baris dan kolom untuk menunjukkan posisi sebuah elemen dalam matriks.
Contoh $b_{12}$ mengacu pada baris pertama dan kolom kedua matriks B.
Secara umum, kita mungkin menggunakan variabel di subskrip, seperti $a_{ij}$ artinya elemen dari matriks $A$ pada baris $i$ dan kolom $j$.

#### Jenis-jenis Matriks

1. Matriks Baris

Matriks baris adalah matriks yang terdiri dari hanya satu baris saja.

- Contoh :

$
A = \begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}
$

2. Matriks Kolom

Matriks kolom adalah matriks yang terdiri dari hanya satu kolom saja.

- Contoh :

$
X = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$

Biasanya matriks ini disebut juga dengan vektor.

3. Matriks nol

Matriks nol adalah matriks yang semua elemen didalam matriks tersebut semuanya bernilai 0.

- Contoh :

$
M = \begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}
$

4. Matriks Persegi

Matriks persegi adalah matriks yang dimana jumlah barisnya sama dengan jumlah kolomnya

- Contoh : 

$
B = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$

$
C = \begin{bmatrix}
1 & 2 & 3\\
3 & 4 & 5\\
5 & 6 & 7
\end{bmatrix}
$

5. Matriks Segitiga
Matriks segitiga ada dua, yaitu segitiga atas dan segitiga bawah. Matriks segitiga atas adalah matriks dimana elemen-elemen yang berada dibawah diagonal utama bernilai nol dan sebaliknya.

- Contoh segitiga atas :

$
E = \begin{bmatrix}
9 & 8 & 7\\
0 & 5 & 4\\
0 & 0 & 1
\end{bmatrix}
$

- Contoh segitiga bawah :

$
E = \begin{bmatrix}
9 & 0 & 0\\
6 & 5 & 0\\
3 & 2 & 1
\end{bmatrix}
$

6. Matriks diagonal

Matriks diagonal adalah matriks dengan elemen selain pada diagonalnya bernilai 0. Diagonal dalam matriks diagonal ada dua yaitu diagonal utama dan sekunder. Jika elemen yang ada pada diagonalnya bernilai sama, maka matriks itu disebut matriks skalar

- Contoh diagonal utama :

$
P = \begin{bmatrix}
1 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 3
\end{bmatrix}
$

- Contoh diagonal sekunder :

$
Q = \begin{bmatrix}
0 & 0 & 1\\
0 & 2 & 0\\
3 & 0 & 0
\end{bmatrix}
$

- Contoh matriks skalar :

$
R = \begin{bmatrix}
2 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 2
\end{bmatrix}
$

7. Matriks datar dan tegak

Matriks datar adalah matriks dengan jumlah kolom lebih besar dari jumlah barisnya. Sementara matriks tegak adalah matriks dengan jumlah baris lebih besar dari jumlah kolomnya.

- Contoh matriks datar :

$
Y = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$

- Contoh matriks tegak :

$
Z = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$

8. Matriks identitas

Matriks identitas merupakan matriks dengan elemen hanya bernilai 0 atau 1.

- Contoh :

$
O = \begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$

#### Implementasi dengan numpy

Cara membuat matriks dengan numpy


In [2]:
import numpy as np
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"C = \n{C}")
print(f"D = \n{D}")

A = 
[[1 3]
 [2 1]]
B = 
[[ 3  0  4]
 [-1 -2  1]]
C = 
[[-2  1]
 [ 4  1]]
D = 
[[2]
 [6]]


#### Cara membuat random matriks dengan numpy

In [3]:
E = np.random.randint(10,size=(3,3))
print(C)

[[-2  1]
 [ 4  1]]


- Setiap di print, maka matriks E akan berubah-ubah

Perlu diingat sebelum menjumlahkan, mengurangkan, atau mmengalikan kedua buah matriks, ukuran dari kedua matriks tersebut harus sama.

Notasi ukuran matriks sebagai berikut :

$A_{ij}$ artinya matriks $A$ mempunyai i baris dan j kolom

#### Cara cek ukuran matriks menggunakan python dan numpy


- Python

In [4]:
ukuran_matriks = len(A),len(A[0])
print(f"Ukuran matriks A adalah = {ukuran_matriks}")

Ukuran matriks A adalah = (2, 2)


- Numpy

In [5]:
print(f"Ukuran matriks A adalah = {A.shape}")

Ukuran matriks A adalah = (2, 2)


Berarti matriks A diatas mempunyai 2 baris dan 2 kolom.

Setelah kita tau beberapa implementasi numpy pada matriks, ada satu jenis matriks lagi yaitu matriks transpose.

##### Matriks Transpose

Matriks transpose adalah transformasi atau perubahan pada elemen-elemen matriks yang awalnya merupakan baris menjadi kolom dan sebaliknya. Matriks dikatakan matriks simetris jika elemen-elemen dari sebuah matriks sama dengan hasil transpose-nya. Sebuah matriks disebut matriks simetri miring pada saat nilai elemennya selain diagonal utama nilainya berlawanan. Notasi matriks transpose adalah $A^T$.

Cara transpose sebuah matriks menggunakan python

In [13]:
print(f"B = \n{B}")

def transpose(a):
    hasil = []
    for i in range(len(a[0])):
        temp = []
        for j in range(len(a)):
            temp.append(a[j][i])
        hasil.append(temp)
    return hasil

hasil = transpose(B)
hasil = np.array(hasil)
print(f"Bt = \n{hasil}")

B = 
[[ 3  0  4]
 [-1 -2  1]]
Bt = 
[[ 3 -1]
 [ 0 -2]
 [ 4  1]]


Cara transpose matriks menggunakan numpy

In [19]:
print(f"B = \n{B}")
trans = np.array(B.transpose())
print(f"Hasil = \n{trans}")

B = 
[[ 3  0  4]
 [-1 -2  1]]
Hasil = 
[[ 3 -1]
 [ 0 -2]
 [ 4  1]]


#### Operasi

##### Cara menjumlahkan dan mengurangkan dua buah matriks dengan python dan numpy

Penjumlahan dua matriks adalah dengan menjumlahkan tiap elemen dari kedua matriks tersebut sesuai dengan posisinya.

Misal $A_{12}$ dijumlahkan dengan $C_{12}$, artinya elemen matriks $A$ pada baris 1 kolom 2 dijumlahkan dengan matriks $C$ dengan posisi elemen yang sama yaitu baris 1 kolom 2 dan seterusnya. 

Pengoperasian penjumlahan dan pengurangan bisa di ilustrasikan dengan notasi sebagai berikut : 

$(A + C)_{ij} = a_{ij} + c_{ij}$

Misal $A + C $ : 

$$
A = \begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}
$$
$$
C = \begin{bmatrix}
-2 & 1\\
4 & 1
\end{bmatrix}
$$
$$
A + C = \begin{bmatrix}
1+(-2) & 3+1\\
2+4 & 1+1
\end{bmatrix}
$$

Menjumlahkan matriks dengan python

In [6]:
AaddC = []
for i in range(len(A)):
    litemp = []
    for j in range(len(A[0])):
        temp = 0
        temp += A[i][j] + C[i][j]
        print(f"{A[i][j]} + {C[i][j]}")
        litemp.append(temp)
    AaddC.append(litemp)
print(AaddC)

1 + -2
3 + 1
2 + 4
1 + 1
[[-1, 4], [6, 2]]


Menjumlahkan matriks dengan Numpy

In [7]:
hasil = A + C
print(f"A + B = \n{hasil}")

A + B = 
[[-1  4]
 [ 6  2]]


Untuk pengurangan, metodenya sama dengan penjumlahan

##### Cara mengalikan dua buah matriks dengan python biasa dan numpy

Perkalian dua matriks adalah dengan mengalikan (misal ada matriks $A$ dan $C$) baris matriks $A$ dengan kolom matriks $C$. Jika banyak kolom dari matriks $A$ adalah sama dengan banyaknya baris matriks $B$, maka kedua matriks tersebut dapat dikalikan dalam dengan bentuk perkalian $A,B$.

Mengalikan matriks dengan python

In [8]:
def perkalian(matrix1,matrix2):
    hasil = []
    if len(matrix1[0]) != len(matrix2):
        print("Tidak bisa mengalikan matriks")
        return None
    else:
        for i in range(len(matrix1)):
            tempp = []
            for j in range(len(matrix2[0])):
                temp = 0
                for k in range(len(matrix2)):
                    temp += matrix1[i][k] * matrix2[k][j]
                tempp.append(temp)
            hasil.append(tempp)
        return hasil

In [14]:
print(f"A = \n{A}")
print(f"C = \n{C}")
hasil = np.array(perkalian(A,C))
print(f"hasil = \n{hasil}")

A = 
[[1 3]
 [2 1]]
C = 
[[-2  1]
 [ 4  1]]
hasil = 
[[10  4]
 [ 0  3]]


Cara mengalikan matriks dengan numpy

Operasi perkalian matriks dengan numpy adalah dengan memakai simbol @

In [9]:
print(A@C)

[[10  4]
 [ 0  3]]


##### Cara mencari determinan matriks menggunakan python

In [1]:
a = [
    [2,1,3],
    [1,4,2],
    [3,1,2],
]
def det(a):
    bantu = a
    for i in range(len(a)):
        for j in range(len(a[0])):
            bantu[i].append(a[i][j])
    kanan = 0
    kiri = 0
    for i in range(len(a)):
        kanan1 = 1
        kiri1 = 1
        for j in range(len(a)):
            # print(bantu[j][len(a)-1-j+i])
            # print(bantu[j][j+i])
            kanan1 *= bantu[j][j+i]
            kiri1 *= bantu[j][len(a)-1-j+i]
        kanan += kanan1
        # print(kiri1)
        kiri += kiri1
    return kanan - kiri
print(det(a))

-17


#### Referensi

- https://fti.ars.ac.id/blog/content/matriks--jenis-jenis-matriks#:~:text=Matriks%20adalah%20suatu%20susunan%20bilangan,sehingga%20membentuk%20jajaran%20persegi%20panjang.&text=Suatu%20matriks%20diberi%20nama%20dengan,anggotanya%20dinyatakan%20dengan%20huruf%20kecil.
- https://www.ruangguru.com/blog/mengenal-matriks-dalam-matematika-pengertian-jenis-dan-transpose
- https://tetrikmatriks.wordpress.com/2017/10/21/pengertian-dan-jenis-matriks/
- https://id.wikipedia.org/wiki/Matriks_diagonal
- https://www.digitalocean.com/community/tutorials/numpy-matrix-transpose-array
- https://www.ruangguru.com/blog/cara-mencari-determinan-dan-invers-matriks
- https://byjus.com/maths/inverse-matrix/
- https://kumparan.com/berita-update/cara-mencari-adjoin-matriks-3x3-dan-contohnya-21KH3nq8dQW
- https://akupintar.id/info-pintar/-/blogs/matriks-pengertian-operasi-determinan-invers-dan-contoh-soal#:~:text=Determinan%20suatu%20matriks%20didefinisikan%20sebagai,A)%20atau%20%7CA%7C