### Tugas Pendahuluan

### **TUGAS 1**
### **SISTEM LINEAR DAN METODE ELIMINASI GAUSSIAN**

**ELIMINASI GAUSSIAN**   
    Eliminasi gauss ditemukan oleh Carl Friedrich Gauss, metode ini dapat dimanfaatkan untuk memecahkan sistem persamaan linear dengan merepresentasikan (mengubah) menjadi bentuk matriks, matriks tersebut lalu diubah kebentuk Eselon Baris melalui Operasi Baris Elementer. Kemudian sistem diselesaikan dengan substitusi balik.   
    
**Bentuk Eselon Baris**    
Suatu matriks memiliki bentuk eselon baris jika memenuhi 3 kriteria berikut   
1. Jika didalam baris terdapat elemen-elemen yang tidak semuanya nol, maka bilangan tak nol pertama di dalam baris tersebut adalah 1.   
2. kalau ada baris-baris yang semua elemennya  bernilai 0 semua, maka baris-baris tersebut harus dikelompokkan dan diletakkan dibagian bawah matriks.   
3. Jika terdapat dua baris berurutan yang memenuhi kriteria pertama, maka angka 1 (pertama/utama) dari baris yang lebih rendah berada lebih kekanan dari angka 1(pertama/utama) baris yang diatasnya.

ADA TIGA OPERASI YANG DAPAT DILAKUKAN
1. Tukarkan posisi kedua persamaan.

2. Kalikan persamaan dengan bilangan apa pun yang bukan nol.

3. Gantikan suatu persamaan dengan jumlah persamaan itu sendiri dan kelipatan persamaan lainnya.


CONTOH    
Selesaikan persamaan berikut ini dengan metode Eliminasi Gaussian
$$
8x_1+9x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2+x_3=5\\
$$

In [1]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
A = np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


In [3]:
a2 = RowAdd(A,2,0,-4)
print(a2)

[[ 0.  5. -3. -1.]
 [ 1.  2.  3.  9.]
 [ 2.  1.  1.  5.]]


In [4]:
a3 = RowSwap(a2,0,2)
print(a3)

[[ 2.  1.  1.  5.]
 [ 1.  2.  3.  9.]
 [ 0.  5. -3. -1.]]


In [5]:
a4 = RowAdd(a3,1,0,-2)
print(a4)

[[  0.  -3.  -5. -13.]
 [  1.   2.   3.   9.]
 [  0.   5.  -3.  -1.]]


In [6]:
a5 = RowSwap(a4,0,1)
print(a5)

[[  1.   2.   3.   9.]
 [  0.  -3.  -5. -13.]
 [  0.   5.  -3.  -1.]]


In [7]:
a6 = RowScale(a5,1,5)
print(a6)

[[  1.   2.   3.   9.]
 [  0. -15. -25. -65.]
 [  0.   5.  -3.  -1.]]


In [8]:
a7 = RowScale(a6,2,3)
print(a7)

[[  1.   2.   3.   9.]
 [  0. -15. -25. -65.]
 [  0.  15.  -9.  -3.]]


In [9]:
a8 = RowAdd(a7,1,2,1)
print(a8)

[[  1.   2.   3.   9.]
 [  0. -15. -25. -65.]
 [  0.   0. -34. -68.]]


In [10]:
a9 = RowScale(a8,2,-1/34)
print(a9)

[[  1.   2.   3.   9.]
 [  0. -15. -25. -65.]
 [ -0.  -0.   1.   2.]]


In [11]:
a10 = RowScale(a9,1,-1/5)
print(a10)

[[ 1.  2.  3.  9.]
 [-0.  3.  5. 13.]
 [-0. -0.  1.  2.]]


Dari matriks terakhir tersebut sudah memenuhi ketiga kriteria bentuk eselon baris. Selanjutnya tinggal mengubahnya kembali menjadi sistem persamaan linear

$$
x_1+2x_2+3x_3=9\\
3x_2+5x_3=13\\
x_3=2
$$