## Aljabar Matrix

### Pengertian Matriks

- Matrix adalah larik bilangan dua dimensi. Komputas matriks menggunakan numoy, dengan menggunakan array
$$
A =\begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}
$$

- Dimensi atau ukuran matriks ditentukan dengan jumlah baris dan kolom
- Jumlah baris biasanya dicantumkan terlebih dahulu

    Maksudnya : 

    $A_{ij}$

    Matrik diatas mempunyai sebanyak i baris dan sebanyak j kolom

- Matriks yang hanya memiliki 1 kolom, seperti D, bisa disebut vektor

    Contoh :
$$
D = \begin{bmatrix}
1\\
2
\end{bmatrix}
$$

- Menggunakan huruf besar untuk memberi nama matriks
- Elemen matriks dinyatakan dengan huruf kecil dengan subskrip untuk menunjukkan posisi entri dalam matriks.
    - Contoh $b_{12}$ mengacu pada baris pertama dan kolom kedua matriks B.
    - Secara umum, kita mungkin menggunakan variabel di subskrip, seperti $a_{ij}$ artinya elemen dari a baris i dan kolom j.


### Implementasi dengan numpy

Cara membuat matriks dengan numpy


In [1]:
import numpy as np
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"C = \n{C}")
print(f"D = \n{D}")

A = 
[[1 3]
 [2 1]]
B = 
[[ 3  0  4]
 [-1 -2  1]]
C = 
[[-2  1]
 [ 4  1]]
D = 
[[2]
 [6]]


#### Cara membuat random matriks dengan numpy

In [2]:
E = np.random.randint(10,size=(3,3))
print(C)

[[-2  1]
 [ 4  1]]


- Setiap di print, maka matriks E akan berubah-ubah

Perlu diingat sebelum menjumlahkan, mengurangkan, atau mmengalikan kedua buah matriks, ukuran dari kedua matriks tersebut harus sama.

Notasi ukuran matriks sebagai berikut :

$A_{ij}$ artinya matriks $A$ mempunyai i baris dan j kolom

##### Cara cek ukuran matriks menggunakan python dan numpy


- Python

In [3]:
panjang_matriks = len(A),len(A[0])
print(f"Ukuran matriks A adalah = {panjang_matriks}")

Ukuran matriks A adalah = (2, 2)


- Numpy

In [4]:
print(f"Ukuran matriks A adalah = {A.shape}")

Ukuran matriks A adalah = (2, 2)


Berarti matriks A diatas mempunyai 2 baris dan 2 kolom.

#### Cara menjumlahkan dan mengurangkan dua buah matriks dengan python dan numpy

Penjumlahan dua matriks adalah dengan menjumlahkan tiap elemen dari kedua matriks tersebut sesuai dengan posisinya.

Misal $A_{12}$ dijumlahkan dengan $C_{12}$, artinya elemen matriks $A$ pada baris 1 kolom 2 dijumlahkan dengan matriks $C$ dengan posisi elemen yang sama yaitu baris 1 kolom 2 dan seterusnya. 

Pengoperasian penjumlahan dan pengurangan bisa di ilustrasikan dengan notasi sebagai berikut : 

$(A + C)_{ij} = a_{ij} + c_{ij}$

Misal $A + C $ : 

$$
A = \begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}
$$
$$
C = \begin{bmatrix}
-2 & 1\\
4 & 1
\end{bmatrix}
$$
$$
A + C = \begin{bmatrix}
1+(-2) & 3+1\\
2+4 & 1+1
\end{bmatrix}
$$

Menjumlahkan matriks dengan python

In [5]:
AaddC = []
for i in range(len(A)):
    litemp = []
    for j in range(len(A[0])):
        temp = 0
        temp += A[i][j] + C[i][j]
        print(f"{A[i][j]} + {C[i][j]}")
        litemp.append(temp)
    AaddC.append(litemp)
print(AaddC)

1 + -2
3 + 1
2 + 4
1 + 1
[[-1, 4], [6, 2]]


Menjumlahkan matriks dengan Numpy

In [6]:
hasil = A + C
print(f"A + B = \n{hasil}")

A + B = 
[[-1  4]
 [ 6  2]]


Untuk pengurangan, metodenya sama dengan penjumlahan

#### Cara mengalikan dua buah matriks dengan python biasa dan numpy

Perkalian dua matriks adalah dengan mengalikan (misal ada matriks $A$ dan $C$) baris matriks $A$ dengan kolom matriks $C$. Jika banyak kolom dari matriks $A$ adalah sama dengan banyaknya baris matriks $B$, maka kedua matriks tersebut dapat dikalikan dalam dengan bentuk perkalian $A,B$.

Mengalikan matriks dengan python

In [7]:
def perkalian(matrix1,matrix2):
    hasil = []
    if len(matrix1[0]) != len(matrix2):
        print("Tidak bisa mengalikan matriks")
        return None
    else:
        for i in range(len(matrix1)):
            tempp = []
            for j in range(len(matrix2[0])):
                temp = 0
                for k in range(len(matrix2)):
                    temp += matrix1[i][k] * matrix2[k][j]
                tempp.append(temp)
            hasil.append(tempp)
        return hasil

In [8]:
print(A)
print(C)

print(perkalian(A,C))

[[1 3]
 [2 1]]
[[-2  1]
 [ 4  1]]
[[10, 4], [0, 3]]


Cara mengalikan matriks dengan numpy

Operasi perkalian matriks dengan numpy adalah dengan memakai simbol @

In [9]:
print(A@C)

[[10  4]
 [ 0  3]]
